"""baseline - matches current schema

Revision ID: 3c638847f480
Revises: 
Create Date: 2026-08-14 15:14:18.251787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c638847f480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('bedrock_api_key',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('solution_packages', schema=None) as batch_op:
        batch_op.alter_column('assumptions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_packages', schema=None) as batch_op:
        batch_op.alter_column('assumptions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('bedrock_api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
