"""widen service_packages.monthly_price to fit real pricing notes

Revision ID: 7c6dd0c94313
Revises: 3c638847f480
Create Date: 2026-08-14 17:21:08.599431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6dd0c94313'
down_revision: Union[str, Sequence[str], None] = '3c638847f480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_packages', schema=None) as batch_op:
        batch_op.alter_column('monthly_price',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_packages', schema=None) as batch_op:
        batch_op.alter_column('monthly_price',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
